/*
 * VT100Lamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Devices;

public class VT100Lamps extends javax.swing.JPanel {

    /** Creates new form VT100Lamps */
    public VT100Lamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lamp1 = new Devices.Lamp();
        lamp2 = new Devices.Lamp();
        lamp3 = new Devices.Lamp();
        lamp4 = new Devices.Lamp();
        lamp5 = new Devices.Lamp();
        lamp6 = new Devices.Lamp();
        lamp7 = new Devices.Lamp();
        Digital = new javax.swing.JLabel();
        VT100 = new javax.swing.JLabel();
        Right = new javax.swing.JLabel();
        Left = new javax.swing.JLabel();
        Upper = new javax.swing.JLabel();
        CenterPanel = new javax.swing.JPanel();
        LowerText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setMinimumSize(new java.awt.Dimension(355, 225));
        setPreferredSize(new java.awt.Dimension(710, 450));
        setLayout(new java.awt.GridBagLayout());

        lamp1.setBackground(new java.awt.Color(51, 51, 51));
        lamp1.setForeground(new java.awt.Color(51, 51, 51));
        lamp1.setMaximumSize(new java.awt.Dimension(30, 20));
        lamp1.setMinimumSize(new java.awt.Dimension(15, 10));
        lamp1.setPreferredSize(new java.awt.Dimension(30, 20));
        lamp1.setState(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(lamp1, gridBagConstraints);

        lamp2.setBackground(new java.awt.Color(51, 51, 51));
        lamp2.setForeground(new java.awt.Color(51, 51, 51));
        lamp2.setMaximumSize(new java.awt.Dimension(30, 20));
        lamp2.setMinimumSize(new java.awt.Dimension(15, 10));
        lamp2.setPreferredSize(new java.awt.Dimension(30, 20));
        lamp2.setState(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        add(lamp2, gridBagConstraints);

        lamp3.setBackground(new java.awt.Color(51, 51, 51));
        lamp3.setForeground(new java.awt.Color(51, 51, 51));
        lamp3.setMaximumSize(new java.awt.Dimension(30, 20));
        lamp3.setMinimumSize(new java.awt.Dimension(15, 10));
        lamp3.setPreferredSize(new java.awt.Dimension(30, 20));
        lamp3.setState(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        add(lamp3, gridBagConstraints);

        lamp4.setBackground(new java.awt.Color(51, 51, 51));
        lamp4.setForeground(new java.awt.Color(51, 51, 51));
        lamp4.setMaximumSize(new java.awt.Dimension(30, 20));
        lamp4.setMinimumSize(new java.awt.Dimension(15, 10));
        lamp4.setPreferredSize(new java.awt.Dimension(30, 20));
        lamp4.setState(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        add(lamp4, gridBagConstraints);

        lamp5.setBackground(new java.awt.Color(51, 51, 51));
        lamp5.setForeground(new java.awt.Color(51, 51, 51));
        lamp5.setMaximumSize(new java.awt.Dimension(30, 20));
        lamp5.setMinimumSize(new java.awt.Dimension(15, 10));
        lamp5.setPreferredSize(new java.awt.Dimension(30, 20));
        lamp5.setState(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        add(lamp5, gridBagConstraints);

        lamp6.setBackground(new java.awt.Color(51, 51, 51));
        lamp6.setForeground(new java.awt.Color(51, 51, 51));
        lamp6.setMaximumSize(new java.awt.Dimension(30, 20));
        lamp6.setMinimumSize(new java.awt.Dimension(15, 10));
        lamp6.setPreferredSize(new java.awt.Dimension(30, 20));
        lamp6.setState(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        add(lamp6, gridBagConstraints);

        lamp7.setBackground(new java.awt.Color(51, 51, 51));
        lamp7.setForeground(new java.awt.Color(51, 51, 51));
        lamp7.setMaximumSize(new java.awt.Dimension(30, 20));
        lamp7.setMinimumSize(new java.awt.Dimension(15, 10));
        lamp7.setPreferredSize(new java.awt.Dimension(30, 20));
        lamp7.setState(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        add(lamp7, gridBagConstraints);

        Digital.setBackground(java.awt.Color.darkGray);
        Digital.setFont(new java.awt.Font("Dialog", 0, 18));
        Digital.setForeground(new java.awt.Color(255, 255, 255));
        Digital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Digital.setText("d|i|g|i|t|a|l");
        Digital.setMinimumSize(new java.awt.Dimension(112, 20));
        Digital.setPreferredSize(new java.awt.Dimension(224, 40));
        Digital.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        add(Digital, gridBagConstraints);

        VT100.setBackground(java.awt.Color.darkGray);
        VT100.setFont(new java.awt.Font("Dialog", 0, 18));
        VT100.setForeground(new java.awt.Color(204, 0, 0));
        VT100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VT100.setText("  VT100");
        VT100.setMinimumSize(new java.awt.Dimension(112, 20));
        VT100.setPreferredSize(new java.awt.Dimension(224, 40));
        VT100.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        add(VT100, gridBagConstraints);

        Right.setBackground(java.awt.Color.darkGray);
        Right.setMinimumSize(new java.awt.Dimension(10, 222));
        Right.setPreferredSize(new java.awt.Dimension(20, 444));
        Right.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(Right, gridBagConstraints);

        Left.setBackground(java.awt.Color.darkGray);
        Left.setMinimumSize(new java.awt.Dimension(10, 222));
        Left.setPreferredSize(new java.awt.Dimension(20, 444));
        Left.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(Left, gridBagConstraints);

        Upper.setBackground(java.awt.Color.darkGray);
        Upper.setMinimumSize(new java.awt.Dimension(329, 10));
        Upper.setPreferredSize(new java.awt.Dimension(658, 20));
        Upper.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        add(Upper, gridBagConstraints);

        CenterPanel.setBackground(new java.awt.Color(255, 255, 255));
        CenterPanel.setMinimumSize(new java.awt.Dimension(329, 192));
        CenterPanel.setPreferredSize(new java.awt.Dimension(658, 384));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        add(CenterPanel, gridBagConstraints);

        LowerText.setBackground(java.awt.Color.darkGray);
        LowerText.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 11));
        LowerText.setForeground(new java.awt.Color(255, 255, 255));
        LowerText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LowerText.setText("online local  lock    L1      L2      L3     L4");
        LowerText.setMinimumSize(new java.awt.Dimension(105, 10));
        LowerText.setPreferredSize(new java.awt.Dimension(210, 20));
        LowerText.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 7;
        add(LowerText, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    public java.awt.Dimension setPanel(javax.swing.JPanel panel) {
        java.awt.GridBagConstraints gridBagConstraints;
        java.awt.Dimension dimnew = panel.getPreferredSize();
        java.awt.Dimension dimold = CenterPanel.getPreferredSize();
        java.awt.Dimension dimback = new java.awt.Dimension(0,0);
        ratiox = dimnew.getWidth()/ dimold.getWidth();
        ratioy = dimnew.getHeight()/ dimold.getHeight();
        remove(CenterPanel);
        this.CenterPanel = panel;
        //CenterPanel.setBackground(new java.awt.Color(255, 255, 255));
        CenterPanel.setPreferredSize(dimnew);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        add(this.CenterPanel, gridBagConstraints);
        this.setBackground(java.awt.Color.darkGray);

        adjust(Upper);
        double panelwidth = Upper.getSize().getWidth();
        adjust(Left);
        double panelheight = Left.getSize().getHeight();
        panelwidth = panelwidth + Left.getSize().getWidth()*2;
        adjust(Right);
        adjust(LowerText);
        LowerText.setFont(new java.awt.Font("SansSerif", 0, (int) (11*ratiox+0.4)));
        adjust(Digital);
        Digital.setFont(new java.awt.Font("SansSerif", 1, (int) (17*ratiox+0.4)));
        adjust(VT100);
        VT100.setFont(new java.awt.Font("SansSerif", 1, (int) (17*ratiox+0.4)));
        adjust(lamp1);adjust(lamp2);adjust(lamp3);adjust(lamp4);
        adjust(lamp5);adjust(lamp6);adjust(lamp7);
        adjust(this);
        dimback.setSize(panelwidth,panelheight);
        return dimback;
    }

    private void adjust(javax.swing.JComponent comp) {
        java.awt.Dimension dimold = comp.getPreferredSize();
        java.awt.Dimension dimnew = new java.awt.Dimension();
        dimnew.setSize(dimold.getWidth()*ratiox,dimold.getHeight()*ratioy);
        comp.setPreferredSize(dimnew);
        comp.setSize(dimnew);
    }

    public void setState(int state) {
        this.state = state;
        lamp1.setState(state&0100);
        lamp2.setState(state&040);
        lamp3.setState(state&020);
        lamp4.setState(state&010);
        lamp5.setState(state&04);
        lamp6.setState(state&02);
        lamp7.setState(state&01);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel CenterPanel;
    private javax.swing.JLabel Digital;
    private javax.swing.JLabel Left;
    private javax.swing.JLabel LowerText;
    private javax.swing.JLabel Right;
    private javax.swing.JLabel Upper;
    private javax.swing.JLabel VT100;
    private Devices.Lamp lamp1;
    private Devices.Lamp lamp2;
    private Devices.Lamp lamp3;
    private Devices.Lamp lamp4;
    private Devices.Lamp lamp5;
    private Devices.Lamp lamp6;
    private Devices.Lamp lamp7;
    // End of variables declaration//GEN-END:variables
    private int state=-1;
    double ratiox;
    double ratioy;

}
