/*
 * BusLamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Panel;

public class AcLamps extends javax.swing.JPanel {

    /** Creates new form maLamps */
    public AcLamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acLamp0 = new Panel.XLamp();
        acLamp1 = new Panel.XLamp();
        acLamp2 = new Panel.XLamp();
        acLamp3 = new Panel.XLamp();
        acLamp4 = new Panel.XLamp();
        acLamp5 = new Panel.XLamp();
        acLamp6 = new Panel.XLamp();
        acLamp7 = new Panel.XLamp();
        acLamp8 = new Panel.XLamp();
        acLamp9 = new Panel.XLamp();
        acLamp10 = new Panel.XLamp();
        acLamp11 = new Panel.XLamp();

        setFont(new java.awt.Font("Dialog", 0, 8));
        setMaximumSize(new java.awt.Dimension(312, 12));
        setMinimumSize(new java.awt.Dimension(156, 6));
        setPreferredSize(new java.awt.Dimension(312, 12));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        acLamp0.setBackground(new java.awt.Color(193, 77, 28));
        acLamp0.setForeground(new java.awt.Color(0, 0, 0));
        acLamp0.setDoubleBuffered(true);
        acLamp0.setEdge(1);
        acLamp0.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp0.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp0.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp0.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp0.setState(false);
        acLamp0.setText("0");
        add(acLamp0, new java.awt.GridBagConstraints());

        acLamp1.setBackground(new java.awt.Color(193, 77, 28));
        acLamp1.setDoubleBuffered(true);
        acLamp1.setEdge(1);
        acLamp1.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp1.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp1.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp1.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp1.setState(false);
        acLamp1.setText("1");
        add(acLamp1, new java.awt.GridBagConstraints());

        acLamp2.setBackground(new java.awt.Color(193, 77, 29));
        acLamp2.setDoubleBuffered(true);
        acLamp2.setEdge(1);
        acLamp2.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp2.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp2.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp2.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp2.setState(false);
        acLamp2.setText("2");
        add(acLamp2, new java.awt.GridBagConstraints());

        acLamp3.setBackground(new java.awt.Color(193, 132, 28));
        acLamp3.setDoubleBuffered(true);
        acLamp3.setEdge(1);
        acLamp3.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp3.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp3.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp3.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp3.setState(false);
        acLamp3.setText("3");
        add(acLamp3, new java.awt.GridBagConstraints());

        acLamp4.setBackground(new java.awt.Color(193, 132, 28));
        acLamp4.setDoubleBuffered(true);
        acLamp4.setEdge(1);
        acLamp4.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp4.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp4.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp4.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp4.setState(false);
        acLamp4.setText("4");
        add(acLamp4, new java.awt.GridBagConstraints());

        acLamp5.setBackground(new java.awt.Color(193, 132, 28));
        acLamp5.setDoubleBuffered(true);
        acLamp5.setEdge(1);
        acLamp5.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp5.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp5.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp5.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp5.setState(false);
        acLamp5.setText("5");
        add(acLamp5, new java.awt.GridBagConstraints());

        acLamp6.setBackground(new java.awt.Color(193, 77, 28));
        acLamp6.setDoubleBuffered(true);
        acLamp6.setEdge(1);
        acLamp6.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp6.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp6.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp6.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp6.setState(false);
        acLamp6.setText("6");
        add(acLamp6, new java.awt.GridBagConstraints());

        acLamp7.setBackground(new java.awt.Color(193, 77, 28));
        acLamp7.setDoubleBuffered(true);
        acLamp7.setEdge(1);
        acLamp7.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp7.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp7.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp7.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp7.setState(false);
        acLamp7.setText("7");
        add(acLamp7, new java.awt.GridBagConstraints());

        acLamp8.setBackground(new java.awt.Color(193, 77, 28));
        acLamp8.setDoubleBuffered(true);
        acLamp8.setEdge(1);
        acLamp8.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp8.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp8.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp8.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp8.setState(false);
        acLamp8.setText("8");
        add(acLamp8, new java.awt.GridBagConstraints());

        acLamp9.setBackground(new java.awt.Color(193, 132, 28));
        acLamp9.setDoubleBuffered(true);
        acLamp9.setEdge(1);
        acLamp9.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp9.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp9.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp9.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp9.setState(false);
        acLamp9.setText("9");
        add(acLamp9, new java.awt.GridBagConstraints());

        acLamp10.setBackground(new java.awt.Color(193, 132, 28));
        acLamp10.setDoubleBuffered(true);
        acLamp10.setEdge(1);
        acLamp10.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp10.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp10.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp10.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp10.setState(false);
        acLamp10.setText("10");
        add(acLamp10, new java.awt.GridBagConstraints());

        acLamp11.setBackground(new java.awt.Color(193, 132, 28));
        acLamp11.setDoubleBuffered(true);
        acLamp11.setEdge(1);
        acLamp11.setFont(new java.awt.Font("Dialog", 1, 8));
        acLamp11.setMaximumSize(new java.awt.Dimension(26, 12));
        acLamp11.setMinimumSize(new java.awt.Dimension(13, 6));
        acLamp11.setPreferredSize(new java.awt.Dimension(26, 12));
        acLamp11.setState(false);
        acLamp11.setText("11");
        add(acLamp11, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (this.getWidth() < 300) {
            acLamp0.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp1.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp2.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp3.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp4.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp5.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp6.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp7.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp8.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp9.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp10.setFont(new java.awt.Font("Dialog", 1, 4));
            acLamp11.setFont(new java.awt.Font("Dialog", 1, 4));
        } else {
            acLamp0.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp1.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp2.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp3.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp4.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp5.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp6.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp7.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp8.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp9.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp10.setFont(new java.awt.Font("Dialog", 1, 8));
            acLamp11.setFont(new java.awt.Font("Dialog", 1, 8));
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    /**
     * Setter for property state.
     * @param state New value of property state.
     */
    public void setState(int state) {
        if (this.state!=state) {
            this.state = state;
            acLamp0.setState(state&04000);
            acLamp1.setState(state&02000);
            acLamp2.setState(state&01000);
            acLamp3.setState(state&00400);
            acLamp4.setState(state&00200);
            acLamp5.setState(state&00100);
            acLamp6.setState(state&00040);
            acLamp7.setState(state&00020);
            acLamp8.setState(state&00010);
            acLamp9.setState(state&00004);
            acLamp10.setState(state&00002);
            acLamp11.setState(state&00001);
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.XLamp acLamp0;
    private Panel.XLamp acLamp1;
    private Panel.XLamp acLamp10;
    private Panel.XLamp acLamp11;
    private Panel.XLamp acLamp2;
    private Panel.XLamp acLamp3;
    private Panel.XLamp acLamp4;
    private Panel.XLamp acLamp5;
    private Panel.XLamp acLamp6;
    private Panel.XLamp acLamp7;
    private Panel.XLamp acLamp8;
    private Panel.XLamp acLamp9;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property state.
     */
    private int state=-1;


}
