/*
 * BusLamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Panel;

public class BusLamps extends javax.swing.JPanel {

    /** Creates new form maLamps */
    public BusLamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        busLamp0 = new Panel.Lamp();
        busLamp1 = new Panel.Lamp();
        busLamp2 = new Panel.Lamp();
        busLamp3 = new Panel.Lamp();
        busLamp4 = new Panel.Lamp();
        busLamp5 = new Panel.Lamp();
        busLamp6 = new Panel.Lamp();
        busLamp7 = new Panel.Lamp();
        busLamp8 = new Panel.Lamp();
        busLamp9 = new Panel.Lamp();
        busLamp10 = new Panel.Lamp();
        busLamp11 = new Panel.Lamp();

        setLayout(new java.awt.GridBagLayout());

        setMaximumSize(new java.awt.Dimension(312, 10));
        setMinimumSize(new java.awt.Dimension(156, 5));
        setPreferredSize(new java.awt.Dimension(312, 10));
        busLamp0.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp0.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp0.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp0, new java.awt.GridBagConstraints());

        busLamp1.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp1.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp1.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp1, new java.awt.GridBagConstraints());

        busLamp2.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp2.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp2.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp2, new java.awt.GridBagConstraints());

        busLamp3.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp3.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp3.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp3, new java.awt.GridBagConstraints());

        busLamp4.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp4.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp4.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp4, new java.awt.GridBagConstraints());

        busLamp5.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp5.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp5.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp5, new java.awt.GridBagConstraints());

        busLamp6.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp6.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp6.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp6, new java.awt.GridBagConstraints());

        busLamp7.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp7.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp7.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp7, new java.awt.GridBagConstraints());

        busLamp8.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp8.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp8.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp8, new java.awt.GridBagConstraints());

        busLamp9.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp9.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp9.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp9, new java.awt.GridBagConstraints());

        busLamp10.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp10.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp10.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp10, new java.awt.GridBagConstraints());

        busLamp11.setMaximumSize(new java.awt.Dimension(26, 10));
        busLamp11.setMinimumSize(new java.awt.Dimension(13, 5));
        busLamp11.setPreferredSize(new java.awt.Dimension(26, 10));
        add(busLamp11, new java.awt.GridBagConstraints());

    }//GEN-END:initComponents

    /**
     * Setter for property state.
     * @param state New value of property state.
     */
    public void setState(int state) {
        if (this.state!=state) {
            this.state = state;
            busLamp0.setState(state&04000);
            busLamp1.setState(state&02000);
            busLamp2.setState(state&01000);
            busLamp3.setState(state&00400);
            busLamp4.setState(state&00200);
            busLamp5.setState(state&00100);
            busLamp6.setState(state&00040);
            busLamp7.setState(state&00020);
            busLamp8.setState(state&00010);
            busLamp9.setState(state&00004);
            busLamp10.setState(state&00002);
            busLamp11.setState(state&00001);
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.Lamp busLamp0;
    private Panel.Lamp busLamp1;
    private Panel.Lamp busLamp10;
    private Panel.Lamp busLamp11;
    private Panel.Lamp busLamp2;
    private Panel.Lamp busLamp3;
    private Panel.Lamp busLamp4;
    private Panel.Lamp busLamp5;
    private Panel.Lamp busLamp6;
    private Panel.Lamp busLamp7;
    private Panel.Lamp busLamp8;
    private Panel.Lamp busLamp9;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property state.
     */
    private int state=-1;

}
