/*
 * BusLamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Panel;

public class DataLamps extends javax.swing.JPanel {

    /** Creates new form maLamps */
    public DataLamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataLamp0 = new Panel.XLamp();
        dataLamp1 = new Panel.XLamp();
        dataLamp2 = new Panel.XLamp();
        dataLamp3 = new Panel.XLamp();
        dataLamp4 = new Panel.XLamp();
        dataLamp5 = new Panel.XLamp();
        dataLamp6 = new Panel.XLamp();
        dataLamp7 = new Panel.XLamp();
        dataLamp8 = new Panel.XLamp();
        dataLamp9 = new Panel.XLamp();
        dataLamp10 = new Panel.XLamp();
        dataLamp11 = new Panel.XLamp();

        setFont(new java.awt.Font("Dialog", 0, 8));
        setMaximumSize(new java.awt.Dimension(312, 12));
        setMinimumSize(new java.awt.Dimension(156, 6));
        setPreferredSize(new java.awt.Dimension(312, 12));
        setLayout(new java.awt.GridBagLayout());

        dataLamp0.setBackground(new java.awt.Color(193, 77, 28));
        dataLamp0.setForeground(new java.awt.Color(0, 0, 0));
        dataLamp0.setDoubleBuffered(true);
        dataLamp0.setEdge(1);
        dataLamp0.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp0.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp0.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp0.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp0.setState(false);
        dataLamp0.setText("");
        add(dataLamp0, new java.awt.GridBagConstraints());

        dataLamp1.setBackground(new java.awt.Color(193, 77, 28));
        dataLamp1.setDoubleBuffered(true);
        dataLamp1.setEdge(1);
        dataLamp1.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp1.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp1.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp1.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp1.setState(false);
        dataLamp1.setText("");
        add(dataLamp1, new java.awt.GridBagConstraints());

        dataLamp2.setBackground(new java.awt.Color(193, 77, 29));
        dataLamp2.setDoubleBuffered(true);
        dataLamp2.setEdge(1);
        dataLamp2.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp2.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp2.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp2.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp2.setState(false);
        dataLamp2.setText("");
        add(dataLamp2, new java.awt.GridBagConstraints());

        dataLamp3.setBackground(new java.awt.Color(193, 132, 28));
        dataLamp3.setDoubleBuffered(true);
        dataLamp3.setEdge(1);
        dataLamp3.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp3.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp3.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp3.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp3.setState(false);
        dataLamp3.setText("");
        add(dataLamp3, new java.awt.GridBagConstraints());

        dataLamp4.setBackground(new java.awt.Color(193, 132, 28));
        dataLamp4.setDoubleBuffered(true);
        dataLamp4.setEdge(1);
        dataLamp4.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp4.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp4.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp4.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp4.setState(false);
        dataLamp4.setText("");
        add(dataLamp4, new java.awt.GridBagConstraints());

        dataLamp5.setBackground(new java.awt.Color(193, 132, 28));
        dataLamp5.setDoubleBuffered(true);
        dataLamp5.setEdge(1);
        dataLamp5.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp5.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp5.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp5.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp5.setState(false);
        dataLamp5.setText("");
        add(dataLamp5, new java.awt.GridBagConstraints());

        dataLamp6.setBackground(new java.awt.Color(193, 77, 28));
        dataLamp6.setDoubleBuffered(true);
        dataLamp6.setEdge(1);
        dataLamp6.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp6.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp6.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp6.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp6.setState(false);
        dataLamp6.setText("");
        add(dataLamp6, new java.awt.GridBagConstraints());

        dataLamp7.setBackground(new java.awt.Color(193, 77, 28));
        dataLamp7.setDoubleBuffered(true);
        dataLamp7.setEdge(1);
        dataLamp7.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp7.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp7.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp7.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp7.setState(false);
        dataLamp7.setText("");
        add(dataLamp7, new java.awt.GridBagConstraints());

        dataLamp8.setBackground(new java.awt.Color(193, 77, 28));
        dataLamp8.setDoubleBuffered(true);
        dataLamp8.setEdge(1);
        dataLamp8.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp8.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp8.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp8.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp8.setState(false);
        dataLamp8.setText("");
        add(dataLamp8, new java.awt.GridBagConstraints());

        dataLamp9.setBackground(new java.awt.Color(193, 132, 28));
        dataLamp9.setDoubleBuffered(true);
        dataLamp9.setEdge(1);
        dataLamp9.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp9.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp9.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp9.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp9.setState(false);
        dataLamp9.setText("");
        add(dataLamp9, new java.awt.GridBagConstraints());

        dataLamp10.setBackground(new java.awt.Color(193, 132, 28));
        dataLamp10.setDoubleBuffered(true);
        dataLamp10.setEdge(1);
        dataLamp10.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp10.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp10.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp10.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp10.setState(false);
        dataLamp10.setText("");
        add(dataLamp10, new java.awt.GridBagConstraints());

        dataLamp11.setBackground(new java.awt.Color(193, 132, 28));
        dataLamp11.setDoubleBuffered(true);
        dataLamp11.setEdge(1);
        dataLamp11.setFont(new java.awt.Font("Dialog", 1, 8));
        dataLamp11.setMaximumSize(new java.awt.Dimension(26, 12));
        dataLamp11.setMinimumSize(new java.awt.Dimension(13, 6));
        dataLamp11.setPreferredSize(new java.awt.Dimension(26, 12));
        dataLamp11.setState(false);
        dataLamp11.setText("");
        add(dataLamp11, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Setter for property state.
     * @param state New value of property state.
     */
    public void setState(int state) {
        if (this.state!=state) {
            this.state = state;
            dataLamp0.setState(state&04000);
            dataLamp1.setState(state&02000);
            dataLamp2.setState(state&01000);
            dataLamp3.setState(state&00400);
            dataLamp4.setState(state&00200);
            dataLamp5.setState(state&00100);
            dataLamp6.setState(state&00040);
            dataLamp7.setState(state&00020);
            dataLamp8.setState(state&00010);
            dataLamp9.setState(state&00004);
            dataLamp10.setState(state&00002);
            dataLamp11.setState(state&00001);
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.XLamp dataLamp0;
    private Panel.XLamp dataLamp1;
    private Panel.XLamp dataLamp10;
    private Panel.XLamp dataLamp11;
    private Panel.XLamp dataLamp2;
    private Panel.XLamp dataLamp3;
    private Panel.XLamp dataLamp4;
    private Panel.XLamp dataLamp5;
    private Panel.XLamp dataLamp6;
    private Panel.XLamp dataLamp7;
    private Panel.XLamp dataLamp8;
    private Panel.XLamp dataLamp9;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property state.
     */
    private int state=-1;


}
