/*
 * EmaLamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Panel;

public class EmaLamps extends javax.swing.JPanel {

    /** Creates new form emaLamps */
    public EmaLamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        emaLamp0 = new Panel.Lamp();
        emaLamp1 = new Panel.Lamp();
        emaLamp2 = new Panel.Lamp();

        setLayout(new java.awt.GridBagLayout());

        setMaximumSize(new java.awt.Dimension(78, 10));
        setMinimumSize(new java.awt.Dimension(39, 5));
        setPreferredSize(new java.awt.Dimension(78, 10));
        emaLamp0.setMaximumSize(new java.awt.Dimension(26, 10));
        emaLamp0.setMinimumSize(new java.awt.Dimension(13, 5));
        emaLamp0.setPreferredSize(new java.awt.Dimension(26, 10));
        add(emaLamp0, new java.awt.GridBagConstraints());

        emaLamp1.setMaximumSize(new java.awt.Dimension(26, 10));
        emaLamp1.setMinimumSize(new java.awt.Dimension(13, 5));
        emaLamp1.setPreferredSize(new java.awt.Dimension(26, 10));
        add(emaLamp1, new java.awt.GridBagConstraints());

        emaLamp2.setMaximumSize(new java.awt.Dimension(26, 10));
        emaLamp2.setMinimumSize(new java.awt.Dimension(13, 5));
        emaLamp2.setPreferredSize(new java.awt.Dimension(26, 10));
        add(emaLamp2, new java.awt.GridBagConstraints());

    }//GEN-END:initComponents

    public void setState(int state) {
        this.state = state;
        emaLamp0.setState(state&04);
        emaLamp1.setState(state&02);
        emaLamp2.setState(state&01);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.Lamp emaLamp0;
    private Panel.Lamp emaLamp1;
    private Panel.Lamp emaLamp2;
    // End of variables declaration//GEN-END:variables
    private int state=-1;

}
