/*
 * JPanel.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Panel;

public class JPanel extends javax.swing.JPanel {

    /** Creates new form JPanel */
    public JPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        lamp1 = new Panel.Lamp();
        lamp2 = new Panel.Lamp();
        lamp3 = new Panel.Lamp();
        lamp4 = new Panel.Lamp();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lamp5 = new Panel.Lamp();
        lamp6 = new Panel.Lamp();
        lamp7 = new Panel.Lamp();

        setLayout(new java.awt.GridBagLayout());

        setPreferredSize(new java.awt.Dimension(300, 215));
        lamp1.setMaximumSize(new java.awt.Dimension(20, 20));
        lamp1.setMinimumSize(new java.awt.Dimension(20, 20));
        lamp1.setPreferredSize(new java.awt.Dimension(30, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(lamp1, gridBagConstraints);

        lamp2.setMaximumSize(new java.awt.Dimension(20, 20));
        lamp2.setMinimumSize(new java.awt.Dimension(20, 20));
        lamp2.setPreferredSize(new java.awt.Dimension(30, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(lamp2, gridBagConstraints);

        lamp3.setMinimumSize(new java.awt.Dimension(20, 20));
        lamp3.setPreferredSize(new java.awt.Dimension(30, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(lamp3, gridBagConstraints);

        lamp4.setMinimumSize(new java.awt.Dimension(20, 20));
        lamp4.setPreferredSize(new java.awt.Dimension(30, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(lamp4, gridBagConstraints);

        jTextArea1.setPreferredSize(new java.awt.Dimension(300, 200));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        add(jTextArea1, gridBagConstraints);

        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        add(jLabel2, gridBagConstraints);

        lamp5.setMinimumSize(new java.awt.Dimension(20, 20));
        lamp5.setPreferredSize(new java.awt.Dimension(30, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        add(lamp5, gridBagConstraints);

        lamp6.setMinimumSize(new java.awt.Dimension(20, 20));
        lamp6.setPreferredSize(new java.awt.Dimension(30, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(lamp6, gridBagConstraints);

        lamp7.setMinimumSize(new java.awt.Dimension(20, 20));
        lamp7.setPreferredSize(new java.awt.Dimension(30, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        add(lamp7, gridBagConstraints);

    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea1;
    private Panel.Lamp lamp1;
    private Panel.Lamp lamp2;
    private Panel.Lamp lamp3;
    private Panel.Lamp lamp4;
    private Panel.Lamp lamp5;
    private Panel.Lamp lamp6;
    private Panel.Lamp lamp7;
    // End of variables declaration//GEN-END:variables

}
