/*
 * BusLamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Panel;

public class MdLamps extends javax.swing.JPanel {

    /** Creates new form maLamps */
    public MdLamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdLamp0 = new Panel.XLamp();
        mdLamp1 = new Panel.XLamp();
        mdLamp2 = new Panel.XLamp();
        mdLamp3 = new Panel.XLamp();
        mdLamp4 = new Panel.XLamp();
        mdLamp5 = new Panel.XLamp();
        mdLamp6 = new Panel.XLamp();
        mdLamp7 = new Panel.XLamp();
        mdLamp8 = new Panel.XLamp();
        mdLamp9 = new Panel.XLamp();
        mdLamp10 = new Panel.XLamp();
        mdLamp11 = new Panel.XLamp();

        setFont(new java.awt.Font("Dialog", 0, 8));
        setMaximumSize(new java.awt.Dimension(312, 12));
        setMinimumSize(new java.awt.Dimension(156, 6));
        setPreferredSize(new java.awt.Dimension(312, 12));
        setLayout(new java.awt.GridBagLayout());

        mdLamp0.setBackground(new java.awt.Color(193, 77, 28));
        mdLamp0.setForeground(new java.awt.Color(0, 0, 0));
        mdLamp0.setDoubleBuffered(true);
        mdLamp0.setEdge(1);
        mdLamp0.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp0.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp0.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp0.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp0.setState(false);
        mdLamp0.setText("");
        add(mdLamp0, new java.awt.GridBagConstraints());

        mdLamp1.setBackground(new java.awt.Color(193, 77, 28));
        mdLamp1.setDoubleBuffered(true);
        mdLamp1.setEdge(1);
        mdLamp1.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp1.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp1.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp1.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp1.setState(false);
        mdLamp1.setText("");
        add(mdLamp1, new java.awt.GridBagConstraints());

        mdLamp2.setBackground(new java.awt.Color(193, 77, 29));
        mdLamp2.setDoubleBuffered(true);
        mdLamp2.setEdge(1);
        mdLamp2.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp2.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp2.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp2.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp2.setState(false);
        mdLamp2.setText("");
        add(mdLamp2, new java.awt.GridBagConstraints());

        mdLamp3.setBackground(new java.awt.Color(193, 132, 28));
        mdLamp3.setDoubleBuffered(true);
        mdLamp3.setEdge(1);
        mdLamp3.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp3.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp3.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp3.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp3.setState(false);
        mdLamp3.setText("");
        add(mdLamp3, new java.awt.GridBagConstraints());

        mdLamp4.setBackground(new java.awt.Color(193, 132, 28));
        mdLamp4.setDoubleBuffered(true);
        mdLamp4.setEdge(1);
        mdLamp4.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp4.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp4.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp4.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp4.setState(false);
        mdLamp4.setText("");
        add(mdLamp4, new java.awt.GridBagConstraints());

        mdLamp5.setBackground(new java.awt.Color(193, 132, 28));
        mdLamp5.setDoubleBuffered(true);
        mdLamp5.setEdge(1);
        mdLamp5.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp5.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp5.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp5.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp5.setState(false);
        mdLamp5.setText("");
        add(mdLamp5, new java.awt.GridBagConstraints());

        mdLamp6.setBackground(new java.awt.Color(193, 77, 28));
        mdLamp6.setDoubleBuffered(true);
        mdLamp6.setEdge(1);
        mdLamp6.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp6.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp6.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp6.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp6.setState(false);
        mdLamp6.setText("");
        add(mdLamp6, new java.awt.GridBagConstraints());

        mdLamp7.setBackground(new java.awt.Color(193, 77, 28));
        mdLamp7.setDoubleBuffered(true);
        mdLamp7.setEdge(1);
        mdLamp7.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp7.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp7.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp7.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp7.setState(false);
        mdLamp7.setText("");
        add(mdLamp7, new java.awt.GridBagConstraints());

        mdLamp8.setBackground(new java.awt.Color(193, 77, 28));
        mdLamp8.setDoubleBuffered(true);
        mdLamp8.setEdge(1);
        mdLamp8.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp8.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp8.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp8.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp8.setState(false);
        mdLamp8.setText("");
        add(mdLamp8, new java.awt.GridBagConstraints());

        mdLamp9.setBackground(new java.awt.Color(193, 132, 28));
        mdLamp9.setDoubleBuffered(true);
        mdLamp9.setEdge(1);
        mdLamp9.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp9.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp9.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp9.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp9.setState(false);
        mdLamp9.setText("");
        add(mdLamp9, new java.awt.GridBagConstraints());

        mdLamp10.setBackground(new java.awt.Color(193, 132, 28));
        mdLamp10.setDoubleBuffered(true);
        mdLamp10.setEdge(1);
        mdLamp10.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp10.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp10.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp10.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp10.setState(false);
        mdLamp10.setText("");
        add(mdLamp10, new java.awt.GridBagConstraints());

        mdLamp11.setBackground(new java.awt.Color(193, 132, 28));
        mdLamp11.setDoubleBuffered(true);
        mdLamp11.setEdge(1);
        mdLamp11.setFont(new java.awt.Font("Dialog", 1, 8));
        mdLamp11.setMaximumSize(new java.awt.Dimension(26, 12));
        mdLamp11.setMinimumSize(new java.awt.Dimension(13, 6));
        mdLamp11.setPreferredSize(new java.awt.Dimension(26, 12));
        mdLamp11.setState(false);
        mdLamp11.setText("");
        add(mdLamp11, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Setter for property state.
     * @param state New value of property state.
     */
    public void setState(int state) {
        if (this.state!=state) {
            this.state = state;
            mdLamp0.setState(state&04000);
            mdLamp1.setState(state&02000);
            mdLamp2.setState(state&01000);
            mdLamp3.setState(state&00400);
            mdLamp4.setState(state&00200);
            mdLamp5.setState(state&00100);
            mdLamp6.setState(state&00040);
            mdLamp7.setState(state&00020);
            mdLamp8.setState(state&00010);
            mdLamp9.setState(state&00004);
            mdLamp10.setState(state&00002);
            mdLamp11.setState(state&00001);
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.XLamp mdLamp0;
    private Panel.XLamp mdLamp1;
    private Panel.XLamp mdLamp10;
    private Panel.XLamp mdLamp11;
    private Panel.XLamp mdLamp2;
    private Panel.XLamp mdLamp3;
    private Panel.XLamp mdLamp4;
    private Panel.XLamp mdLamp5;
    private Panel.XLamp mdLamp6;
    private Panel.XLamp mdLamp7;
    private Panel.XLamp mdLamp8;
    private Panel.XLamp mdLamp9;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property state.
     */
    private int state=-1;


}
