/*
 * BusLamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Panel;

public class MqLamps extends javax.swing.JPanel {

    /** Creates new form maLamps */
    public MqLamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mqLamp0 = new Panel.XLamp();
        mqLamp1 = new Panel.XLamp();
        mqLamp2 = new Panel.XLamp();
        mqLamp3 = new Panel.XLamp();
        mqLamp4 = new Panel.XLamp();
        mqLamp5 = new Panel.XLamp();
        mqLamp6 = new Panel.XLamp();
        mqLamp7 = new Panel.XLamp();
        mqLamp8 = new Panel.XLamp();
        mqLamp9 = new Panel.XLamp();
        mqLamp10 = new Panel.XLamp();
        mqLamp11 = new Panel.XLamp();

        setFont(new java.awt.Font("Dialog", 0, 8));
        setMaximumSize(new java.awt.Dimension(312, 12));
        setMinimumSize(new java.awt.Dimension(156, 6));
        setPreferredSize(new java.awt.Dimension(312, 12));
        setLayout(new java.awt.GridBagLayout());

        mqLamp0.setBackground(new java.awt.Color(193, 77, 28));
        mqLamp0.setForeground(new java.awt.Color(0, 0, 0));
        mqLamp0.setDoubleBuffered(true);
        mqLamp0.setEdge(1);
        mqLamp0.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp0.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp0.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp0.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp0.setState(false);
        mqLamp0.setText("");
        add(mqLamp0, new java.awt.GridBagConstraints());

        mqLamp1.setBackground(new java.awt.Color(193, 77, 28));
        mqLamp1.setDoubleBuffered(true);
        mqLamp1.setEdge(1);
        mqLamp1.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp1.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp1.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp1.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp1.setState(false);
        mqLamp1.setText("");
        add(mqLamp1, new java.awt.GridBagConstraints());

        mqLamp2.setBackground(new java.awt.Color(193, 77, 29));
        mqLamp2.setDoubleBuffered(true);
        mqLamp2.setEdge(1);
        mqLamp2.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp2.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp2.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp2.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp2.setState(false);
        mqLamp2.setText("");
        add(mqLamp2, new java.awt.GridBagConstraints());

        mqLamp3.setBackground(new java.awt.Color(193, 132, 28));
        mqLamp3.setDoubleBuffered(true);
        mqLamp3.setEdge(1);
        mqLamp3.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp3.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp3.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp3.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp3.setState(false);
        mqLamp3.setText("");
        add(mqLamp3, new java.awt.GridBagConstraints());

        mqLamp4.setBackground(new java.awt.Color(193, 132, 28));
        mqLamp4.setDoubleBuffered(true);
        mqLamp4.setEdge(1);
        mqLamp4.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp4.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp4.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp4.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp4.setState(false);
        mqLamp4.setText("");
        add(mqLamp4, new java.awt.GridBagConstraints());

        mqLamp5.setBackground(new java.awt.Color(193, 132, 28));
        mqLamp5.setDoubleBuffered(true);
        mqLamp5.setEdge(1);
        mqLamp5.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp5.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp5.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp5.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp5.setState(false);
        mqLamp5.setText("");
        add(mqLamp5, new java.awt.GridBagConstraints());

        mqLamp6.setBackground(new java.awt.Color(193, 77, 28));
        mqLamp6.setDoubleBuffered(true);
        mqLamp6.setEdge(1);
        mqLamp6.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp6.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp6.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp6.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp6.setState(false);
        mqLamp6.setText("");
        add(mqLamp6, new java.awt.GridBagConstraints());

        mqLamp7.setBackground(new java.awt.Color(193, 77, 28));
        mqLamp7.setDoubleBuffered(true);
        mqLamp7.setEdge(1);
        mqLamp7.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp7.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp7.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp7.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp7.setState(false);
        mqLamp7.setText("");
        add(mqLamp7, new java.awt.GridBagConstraints());

        mqLamp8.setBackground(new java.awt.Color(193, 77, 28));
        mqLamp8.setDoubleBuffered(true);
        mqLamp8.setEdge(1);
        mqLamp8.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp8.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp8.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp8.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp8.setState(false);
        mqLamp8.setText("");
        add(mqLamp8, new java.awt.GridBagConstraints());

        mqLamp9.setBackground(new java.awt.Color(193, 132, 28));
        mqLamp9.setDoubleBuffered(true);
        mqLamp9.setEdge(1);
        mqLamp9.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp9.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp9.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp9.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp9.setState(false);
        mqLamp9.setText("");
        add(mqLamp9, new java.awt.GridBagConstraints());

        mqLamp10.setBackground(new java.awt.Color(193, 132, 28));
        mqLamp10.setDoubleBuffered(true);
        mqLamp10.setEdge(1);
        mqLamp10.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp10.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp10.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp10.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp10.setState(false);
        mqLamp10.setText("");
        add(mqLamp10, new java.awt.GridBagConstraints());

        mqLamp11.setBackground(new java.awt.Color(193, 132, 28));
        mqLamp11.setDoubleBuffered(true);
        mqLamp11.setEdge(1);
        mqLamp11.setFont(new java.awt.Font("Dialog", 1, 8));
        mqLamp11.setMaximumSize(new java.awt.Dimension(26, 12));
        mqLamp11.setMinimumSize(new java.awt.Dimension(13, 6));
        mqLamp11.setPreferredSize(new java.awt.Dimension(26, 12));
        mqLamp11.setState(false);
        mqLamp11.setText("");
        add(mqLamp11, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Setter for property state.
     * @param state New value of property state.
     */
    public void setState(int state) {
        if (this.state!=state) {
            this.state = state;
            mqLamp0.setState(state&04000);
            mqLamp1.setState(state&02000);
            mqLamp2.setState(state&01000);
            mqLamp3.setState(state&00400);
            mqLamp4.setState(state&00200);
            mqLamp5.setState(state&00100);
            mqLamp6.setState(state&00040);
            mqLamp7.setState(state&00020);
            mqLamp8.setState(state&00010);
            mqLamp9.setState(state&00004);
            mqLamp10.setState(state&00002);
            mqLamp11.setState(state&00001);
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.XLamp mqLamp0;
    private Panel.XLamp mqLamp1;
    private Panel.XLamp mqLamp10;
    private Panel.XLamp mqLamp11;
    private Panel.XLamp mqLamp2;
    private Panel.XLamp mqLamp3;
    private Panel.XLamp mqLamp4;
    private Panel.XLamp mqLamp5;
    private Panel.XLamp mqLamp6;
    private Panel.XLamp mqLamp7;
    private Panel.XLamp mqLamp8;
    private Panel.XLamp mqLamp9;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property state.
     */
    private int state=-1;


}
