/*
 * BusLamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Panel;

public class StatusLamps extends javax.swing.JPanel {

    /** Creates new form maLamps */
    public StatusLamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLamp0 = new Panel.XLamp();
        statusLamp1 = new Panel.XLamp();
        statusLamp2 = new Panel.XLamp();
        statusLamp3 = new Panel.XLamp();
        statusLamp4 = new Panel.XLamp();
        statusLamp5 = new Panel.XLamp();
        statusLamp6 = new Panel.XLamp();
        statusLamp7 = new Panel.XLamp();
        statusLamp8 = new Panel.XLamp();
        statusLamp9 = new Panel.XLamp();
        statusLamp10 = new Panel.XLamp();
        statusLamp11 = new Panel.XLamp();

        setFont(new java.awt.Font("Dialog", 0, 8));
        setMaximumSize(new java.awt.Dimension(312, 12));
        setMinimumSize(new java.awt.Dimension(156, 6));
        setPreferredSize(new java.awt.Dimension(312, 12));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        statusLamp0.setBackground(new java.awt.Color(193, 77, 28));
        statusLamp0.setForeground(new java.awt.Color(0, 0, 0));
        statusLamp0.setDoubleBuffered(true);
        statusLamp0.setEdge(3);
        statusLamp0.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp0.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp0.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp0.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp0.setState(false);
        statusLamp0.setText("LINK");
        add(statusLamp0, new java.awt.GridBagConstraints());

        statusLamp1.setBackground(new java.awt.Color(193, 77, 28));
        statusLamp1.setDoubleBuffered(true);
        statusLamp1.setEdge(3);
        statusLamp1.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp1.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp1.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp1.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp1.setState(false);
        statusLamp1.setText("GT");
        add(statusLamp1, new java.awt.GridBagConstraints());

        statusLamp2.setBackground(new java.awt.Color(193, 77, 29));
        statusLamp2.setDoubleBuffered(true);
        statusLamp2.setEdge(3);
        statusLamp2.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp2.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp2.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp2.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp2.setState(false);
        statusLamp2.setText("INT B");
        add(statusLamp2, new java.awt.GridBagConstraints());

        statusLamp3.setBackground(new java.awt.Color(193, 132, 28));
        statusLamp3.setDoubleBuffered(true);
        statusLamp3.setEdge(3);
        statusLamp3.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp3.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp3.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp3.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp3.setState(false);
        statusLamp3.setText("NO IN");
        add(statusLamp3, new java.awt.GridBagConstraints());

        statusLamp4.setBackground(new java.awt.Color(193, 132, 28));
        statusLamp4.setDoubleBuffered(true);
        statusLamp4.setEdge(3);
        statusLamp4.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp4.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp4.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp4.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp4.setState(false);
        statusLamp4.setText("ION");
        add(statusLamp4, new java.awt.GridBagConstraints());

        statusLamp5.setBackground(new java.awt.Color(193, 132, 28));
        statusLamp5.setDoubleBuffered(true);
        statusLamp5.setEdge(3);
        statusLamp5.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp5.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp5.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp5.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp5.setState(false);
        statusLamp5.setText("UM");
        add(statusLamp5, new java.awt.GridBagConstraints());

        statusLamp6.setBackground(new java.awt.Color(193, 77, 28));
        statusLamp6.setDoubleBuffered(true);
        statusLamp6.setEdge(3);
        statusLamp6.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp6.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp6.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp6.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp6.setState(false);
        statusLamp6.setText("IF0");
        add(statusLamp6, new java.awt.GridBagConstraints());

        statusLamp7.setBackground(new java.awt.Color(193, 77, 28));
        statusLamp7.setDoubleBuffered(true);
        statusLamp7.setEdge(3);
        statusLamp7.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp7.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp7.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp7.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp7.setState(false);
        statusLamp7.setText("IF1");
        add(statusLamp7, new java.awt.GridBagConstraints());

        statusLamp8.setBackground(new java.awt.Color(193, 77, 28));
        statusLamp8.setDoubleBuffered(true);
        statusLamp8.setEdge(3);
        statusLamp8.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp8.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp8.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp8.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp8.setState(false);
        statusLamp8.setText("IF2");
        add(statusLamp8, new java.awt.GridBagConstraints());

        statusLamp9.setBackground(new java.awt.Color(193, 132, 28));
        statusLamp9.setDoubleBuffered(true);
        statusLamp9.setEdge(3);
        statusLamp9.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp9.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp9.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp9.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp9.setState(false);
        statusLamp9.setText("DF0");
        add(statusLamp9, new java.awt.GridBagConstraints());

        statusLamp10.setBackground(new java.awt.Color(193, 132, 28));
        statusLamp10.setDoubleBuffered(true);
        statusLamp10.setEdge(3);
        statusLamp10.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp10.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp10.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp10.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp10.setState(false);
        statusLamp10.setText("DF1");
        add(statusLamp10, new java.awt.GridBagConstraints());

        statusLamp11.setBackground(new java.awt.Color(193, 132, 28));
        statusLamp11.setDoubleBuffered(true);
        statusLamp11.setEdge(3);
        statusLamp11.setFont(new java.awt.Font("Dialog", 1, 8));
        statusLamp11.setMaximumSize(new java.awt.Dimension(26, 12));
        statusLamp11.setMinimumSize(new java.awt.Dimension(13, 6));
        statusLamp11.setPreferredSize(new java.awt.Dimension(26, 12));
        statusLamp11.setState(false);
        statusLamp11.setText("DF2");
        add(statusLamp11, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (this.getWidth() < 300) {
            statusLamp0.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp1.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp2.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp3.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp4.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp5.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp6.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp7.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp8.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp9.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp10.setFont(new java.awt.Font("Dialog", 1, 4));
            statusLamp11.setFont(new java.awt.Font("Dialog", 1, 4));
        } else {
            statusLamp0.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp1.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp2.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp3.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp4.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp5.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp6.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp7.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp8.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp9.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp10.setFont(new java.awt.Font("Dialog", 1, 8));
            statusLamp11.setFont(new java.awt.Font("Dialog", 1, 8));
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    /**
     * Setter for property state.
     * @param state New value of property state.
     */
    public void setState(int state) {
        if (this.state!=state) {
            this.state = state;
            statusLamp0.setState(state&04000);
            statusLamp1.setState(state&02000);
            statusLamp2.setState(state&01000);
            statusLamp3.setState(state&00400);
            statusLamp4.setState(state&00200);
            statusLamp5.setState(state&00100);
            statusLamp6.setState(state&00040);
            statusLamp7.setState(state&00020);
            statusLamp8.setState(state&00010);
            statusLamp9.setState(state&00004);
            statusLamp10.setState(state&00002);
            statusLamp11.setState(state&00001);
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Panel.XLamp statusLamp0;
    private Panel.XLamp statusLamp1;
    private Panel.XLamp statusLamp10;
    private Panel.XLamp statusLamp11;
    private Panel.XLamp statusLamp2;
    private Panel.XLamp statusLamp3;
    private Panel.XLamp statusLamp4;
    private Panel.XLamp statusLamp5;
    private Panel.XLamp statusLamp6;
    private Panel.XLamp statusLamp7;
    private Panel.XLamp statusLamp8;
    private Panel.XLamp statusLamp9;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property state.
     */
    private int state=-1;


}
