/*
 * BusLamps.java
 *
 * Created on January 1, 2005, 0:00 PM
 */

/**
 *
 * @author  wvdmark@computer.org
 */

package Test;

public class XLamps extends javax.swing.JPanel {

    /** Creates new form maLamps */
    public XLamps() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busLamp0 = new Test.XLamp();
        busLamp1 = new Test.XLamp();
        busLamp2 = new Test.XLamp();
        busLamp3 = new Test.XLamp();
        busLamp4 = new Test.XLamp();
        busLamp5 = new Test.XLamp();
        busLamp6 = new Test.XLamp();
        busLamp7 = new Test.XLamp();
        busLamp8 = new Test.XLamp();
        busLamp9 = new Test.XLamp();
        busLamp10 = new Test.XLamp();
        busLamp11 = new Test.XLamp();

        setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        setMaximumSize(new java.awt.Dimension(312, 12));
        setMinimumSize(new java.awt.Dimension(156, 6));
        setPreferredSize(new java.awt.Dimension(312, 12));
        setLayout(new java.awt.GridBagLayout());

        busLamp0.setBackground(new java.awt.Color(193, 77, 28));
        busLamp0.setForeground(new java.awt.Color(0, 0, 0));
        busLamp0.setDoubleBuffered(true);
        busLamp0.setEdge(3);
        busLamp0.setFont(new java.awt.Font("Dialog", 1, 8));
        busLamp0.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp0.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp0.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp0.setState(false);
        busLamp0.setText("LINK");
        add(busLamp0, new java.awt.GridBagConstraints());

        busLamp1.setBackground(new java.awt.Color(193, 77, 28));
        busLamp1.setDoubleBuffered(true);
        busLamp1.setEdge(3);
        busLamp1.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        busLamp1.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp1.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp1.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp1.setState(false);
        busLamp1.setText("GT");
        add(busLamp1, new java.awt.GridBagConstraints());

        busLamp2.setBackground(new java.awt.Color(193, 77, 29));
        busLamp2.setDoubleBuffered(true);
        busLamp2.setEdge(3);
        busLamp2.setFont(new java.awt.Font("Dialog", 1, 8));
        busLamp2.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp2.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp2.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp2.setState(false);
        busLamp2.setText("INT B");
        add(busLamp2, new java.awt.GridBagConstraints());

        busLamp3.setBackground(new java.awt.Color(193, 132, 28));
        busLamp3.setDoubleBuffered(true);
        busLamp3.setEdge(3);
        busLamp3.setFont(new java.awt.Font("Dialog", 1, 8));
        busLamp3.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp3.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp3.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp3.setState(false);
        busLamp3.setText("NO IN");
        add(busLamp3, new java.awt.GridBagConstraints());

        busLamp4.setBackground(new java.awt.Color(193, 132, 28));
        busLamp4.setDoubleBuffered(true);
        busLamp4.setEdge(3);
        busLamp4.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        busLamp4.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp4.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp4.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp4.setState(false);
        busLamp4.setText("ION");
        add(busLamp4, new java.awt.GridBagConstraints());

        busLamp5.setBackground(new java.awt.Color(193, 132, 28));
        busLamp5.setDoubleBuffered(true);
        busLamp5.setEdge(3);
        busLamp5.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        busLamp5.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp5.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp5.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp5.setState(false);
        busLamp5.setText("UM");
        add(busLamp5, new java.awt.GridBagConstraints());

        busLamp6.setBackground(new java.awt.Color(193, 77, 28));
        busLamp6.setDoubleBuffered(true);
        busLamp6.setEdge(3);
        busLamp6.setFont(new java.awt.Font("Dialog", 1, 8));
        busLamp6.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp6.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp6.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp6.setState(false);
        busLamp6.setText("IF0");
        add(busLamp6, new java.awt.GridBagConstraints());

        busLamp7.setBackground(new java.awt.Color(193, 77, 28));
        busLamp7.setDoubleBuffered(true);
        busLamp7.setEdge(3);
        busLamp7.setFont(new java.awt.Font("Dialog", 1, 8));
        busLamp7.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp7.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp7.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp7.setState(false);
        busLamp7.setText("IF1");
        add(busLamp7, new java.awt.GridBagConstraints());

        busLamp8.setBackground(new java.awt.Color(193, 77, 28));
        busLamp8.setDoubleBuffered(true);
        busLamp8.setEdge(3);
        busLamp8.setFont(new java.awt.Font("Dialog", 1, 8));
        busLamp8.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp8.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp8.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp8.setState(false);
        busLamp8.setText("IF2");
        add(busLamp8, new java.awt.GridBagConstraints());

        busLamp9.setBackground(new java.awt.Color(193, 132, 28));
        busLamp9.setDoubleBuffered(true);
        busLamp9.setEdge(3);
        busLamp9.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        busLamp9.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp9.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp9.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp9.setState(false);
        busLamp9.setText("DF0");
        add(busLamp9, new java.awt.GridBagConstraints());

        busLamp10.setBackground(new java.awt.Color(193, 132, 28));
        busLamp10.setDoubleBuffered(true);
        busLamp10.setEdge(3);
        busLamp10.setFont(new java.awt.Font("Dialog", 1, 8));
        busLamp10.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp10.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp10.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp10.setState(false);
        busLamp10.setText("DF1");
        add(busLamp10, new java.awt.GridBagConstraints());

        busLamp11.setBackground(new java.awt.Color(193, 132, 28));
        busLamp11.setDoubleBuffered(true);
        busLamp11.setEdge(3);
        busLamp11.setFont(new java.awt.Font("Dialog", 1, 8));
        busLamp11.setMaximumSize(new java.awt.Dimension(26, 12));
        busLamp11.setMinimumSize(new java.awt.Dimension(13, 6));
        busLamp11.setPreferredSize(new java.awt.Dimension(26, 12));
        busLamp11.setState(false);
        busLamp11.setText("DF2");
        add(busLamp11, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Setter for property state.
     * @param state New value of property state.
     */
    public void setState(int state) {
        if (this.state!=state) {
            this.state = state;
            busLamp0.setState(state&04000);
            busLamp1.setState(state&02000);
            busLamp2.setState(state&01000);
            busLamp3.setState(state&00400);
            busLamp4.setState(state&00200);
            busLamp5.setState(state&00100);
            busLamp6.setState(state&00040);
            busLamp7.setState(state&00020);
            busLamp8.setState(state&00010);
            busLamp9.setState(state&00004);
            busLamp10.setState(state&00002);
            busLamp11.setState(state&00001);
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Test.XLamp busLamp0;
    private Test.XLamp busLamp1;
    private Test.XLamp busLamp10;
    private Test.XLamp busLamp11;
    private Test.XLamp busLamp2;
    private Test.XLamp busLamp3;
    private Test.XLamp busLamp4;
    private Test.XLamp busLamp5;
    private Test.XLamp busLamp6;
    private Test.XLamp busLamp7;
    private Test.XLamp busLamp8;
    private Test.XLamp busLamp9;
    // End of variables declaration//GEN-END:variables

    /**
     * Holds value of property state.
     */
    private int state=-1;


}
